#default_controllers:
#    resource: ../../src/Controller
#    type: annotation

ddd_api_controllers:
    resource: ../../src/Model/**/Controller/**/*
    type: annotation
    prefix:
        ru: /api

kernel:
    resource: ../../src/Kernel.php
    type: annotation
